-- create temp table with names of tables and its info for each artificially created database
SELECT 
name as databasename
INTO #alldatabases
FROM sys.databases WHERE database_id > 4;

CREATE TABLE #allcolumnnames (
	TABLE_CATALOG NVARCHAR(128) NULL
	,TABLE_SCHEMA NVARCHAR(128) NULL
	,TABLE_NAME NVARCHAR(128) NOT NULL
	,COLUMN_NAME NVARCHAR(128) NULL
	,ORDINAL_POSITION INT NULL
	,COLUMN_DEFAULT NVARCHAR(4000) NULL
	,IS_NULLABLE NVARCHAR(3) NULL
	,DATA_TYPE NVARCHAR(128) NULL
	,CHARACTER_MAXIMUM_LENGTH INT NULL
	,CHARACTER_OCTET_LENGTH INT NULL
	,NUMERIC_PRECISION TINYINT NULL
	,NUMERIC_PRECISION_RADIX SMALLINT NULL
	,NUMERIC_SCALE INT NULL
	,DATETIME_PRECISION SMALLINT NULL
	,CHARACTER_SET_CATALOG NVARCHAR(128) NULL
	,CHARACTER_SET_SCHEMA NVARCHAR(128) NULL
	,CHARACTER_SET_NAME NVARCHAR(128) NULL
	,COLLATION_CATALOG NVARCHAR(128) NULL
	,COLLATION_SCHEMA NVARCHAR(128) NULL
	,COLLATION_NAME NVARCHAR(128) NULL
	,DOMAIN_CATALOG NVARCHAR(128) NULL
	,DOMAIN_SCHEMA NVARCHAR(128) NULL
	,DOMAIN_NAME NVARCHAR(128) NULL
	,captureddatetime datetime
);

DECLARE @command VARCHAR(MAX);
SET @command = '
USE [?]
IF DB_NAME() IN (SELECT databasename FROM #alldatabases)
BEGIN
	INSERT #allcolumnnames
	SELECT *
			, getdate() as captureddatetime
	FROM ?.INFORMATION_SCHEMA.COLUMNS 
END;'
EXEC sp_MSforeachdb @command
select * from #allcolumnnames
drop table #allcolumnnames
drop table #alldatabases
;

